baseURL = 'https://unaoya.github.io/complex-analysis/'
languageCode = "ja-jp"
title = "複素解析入門"
theme = "hugo-book"
publishDir = "docs"

[params]
  BookTheme = 'auto'
  BookRepo = 'https://github.com/htakeuchi0/htakeuchi0.github.io-sources'
  BookSearch = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true