baseURL = 'https://unaoya.github.io/complex-analysis/'
languageCode = "ja-jp"
title = "複素解析入門"
theme = "hugo-book"
publishDir = "public"

[params]
  BookTheme = 'auto'
  BookSearch = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true